# Site settings
title: Reef Turner
email: reef.turner@gmail.com
author: Reef Turner
description: "the ramblings of a software developer"
baseurl: /
url: 
google_analytics:
animated: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true
