# Site settings
title: Reef Turner
email: reef.turner@gmail.com
author: Reef Turner
description: the ramblings of a software developer
baseurl: ""
url:
google_analytics: UA-55035366-1
animated: true

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true
